version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    rails:
      patterns:
        - "rails"
        - "actioncable"
        - "actionmailbox"
        - "actionmailer"
        - "actionpack"
        - "actiontext"
        - "actionview"
        - "activejob"
        - "activemodel"
        - "activerecord"
        - "activestorage"
        - "activesupport"
        - "railties"
    dev-test:
      dependency-type: "development"
      exclude-patterns:
        - "brakeman"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
