class User < ApplicationRecord
  # extends ...................................................................

  # includes ..................................................................

  # relationships .............................................................
  has_many :sessions, dependent: :destroy

  # validations ...............................................................
  validates :email_address, presence: true, uniqueness: true

  # callbacks .................................................................
  normalizes :email_address, with: ->(e) { e.strip.downcase }

  # scopes ....................................................................

  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  has_secure_password

  # class methods .............................................................

  # public instance methods ...................................................

  # protected instance methods ................................................

  # private instance methods ..................................................
end
